
import placeholderImages from '@/app/lib/placeholder-images.json';

export interface Testimonial {
  name: string;
  course?: string;
  quote: string;
  avatarSrc: string;
  avatarHint: string;
  rating: number;
}

const getAvatar = (id: string) => {
  const placeholder = placeholderImages.find(p => p.id === id);
  if (!placeholder) {
    // Fallback to a default image if not found
    const defaultAvatar = placeholderImages.find(p => p.id === 'avatar-default');
    return {
      src: defaultAvatar?.src || 'https://picsum.photos/seed/avatar-default/100/100',
      hint: defaultAvatar?.hint || 'person avatar'
    };
  }
  return { src: placeholder.src, hint: placeholder.hint };
};

export const testimonials: Testimonial[] = [
  {
    name: 'Tamara Fernández Romero',
    quote: 'Elaboró mi tarta de cumpleaños y ¡estaba deliciosa! Además, me encontraba indecisa en todos los aspectos del proceso y me ayudó un montón a dar forma a la creación. Su atención no tiene precio. Recomiendo 100% y estoy segura de que repetiré. ¡Muchas gracias, Emilia!',
    avatarSrc: getAvatar('avatar1').src,
    avatarHint: getAvatar('avatar1').hint,
    rating: 5,
  },
  {
    name: 'Gustavo Diez',
    quote: '¡La tarta que me hicieron fue un auténtico acierto! La repostería cuidó cada detalle, desde el diseño adorable hasta el sabor delicioso, suave y perfecto para la ocasión. Todo estaba fresco, hecho con mucho cariño y se nota la calidad en cada bocado. ¡Sin duda, repetiré para futuras celebraciones!',
    avatarSrc: getAvatar('avatar2').src,
    avatarHint: getAvatar('avatar2').hint,
    rating: 5,
  },
  {
    name: 'Rey',
    quote: 'The cake for my friend’s birthday was very delicious. Ordered it via WhatsApp before visiting Ourense. Was very satisfied with the communication experience and the overall experience. The chocolate cake was very moist and right amount of sweetness. Thanks for making our day extra special.',
    avatarSrc: getAvatar('avatar3').src,
    avatarHint: getAvatar('avatar3').hint,
    rating: 5,
  },
  {
    name: 'johanna sangronis',
    quote: 'Emilia es un ser que irradia alegría y buena vibra. Gracias por hacer posible una bonita y deliciosa sorpresa para mi hermano. Yo desde Zaragoza la contacte y ella se hizo mi aliada en Ourense. Recomendada 1000%.',
    avatarSrc: getAvatar('avatar4').src,
    avatarHint: getAvatar('avatar4').hint,
    rating: 5,
  },
  {
    name: 'Paula Castro Díaz',
    quote: 'Mi marido me sorprendió este año con esta maravilla de Mortys Cake. El diseño fue una pasada pero lo mejor estaba dentro. Sabor súper equilibrado, dulce pero sin empalagar y se adaptó a las necesidades que le pedimos ya que había una vegana en el grupo y la hizo con productos veganos. Estaba súper rica. Repetiremos sin duda.',
    avatarSrc: getAvatar('avatar5').src,
    avatarHint: getAvatar('avatar5').hint,
    rating: 5,
  },
    {
    name: 'graciela alvez',
    quote: 'Una experiencia maravillosa, nunca comimos una tarta tan exquisita y con tanto detalle y cariño. La tarta para el cumpleaños de mi nieto. Niños y adultos encantados y repitieron... Totalmente agradecida con Emilia.',
    avatarSrc: getAvatar('avatar6').src,
    avatarHint: getAvatar('avatar6').hint,
    rating: 5,
  },
  {
    name: 'Paula Cazorla Salgado',
    quote: 'Muy buena atención, personal encantador! Me hicieron la tarta muy lograda y a buen precio. Estoy encantada 😊 ⭐⭐⭐⭐⭐',
    avatarSrc: getAvatar('avatar7').src,
    avatarHint: getAvatar('avatar7').hint,
    rating: 5,
  },
  {
    name: 'Jeidi Padron',
    quote: 'Unas tartas de ultra lujo, muy originales y novedosas, de exquisito sabor y una textura que deleitan el paladar. Recomiendo los macarons',
    avatarSrc: getAvatar('avatar8').src,
    avatarHint: getAvatar('avatar8').hint,
    rating: 5,
  },
  {
    name: 'Kelly Fernández',
    quote: 'Emilia es un ser de luz. Contacté con ella por una tarta muy concreta que quería,con un tractor y con complementos de agricultura. Por supuesto,Emilia aceptó y superó con creces mis expectativas! La tarta era magnífica,el sabor era increíble.',
    avatarSrc: getAvatar('avatar9').src,
    avatarHint: getAvatar('avatar9').hint,
    rating: 5,
  },
  {
    name: 'Sandra Quintana Caseiro',
    quote: 'Mi hija mayor celebró su cumpleaños en el Mortys Cake, se lo pasaron en grande haciendo cupcakes. Una experiencia totalmente recomendable.',
    avatarSrc: getAvatar('avatar10').src,
    avatarHint: getAvatar('avatar10').hint,
    rating: 5,
  },
  {
    name: 'xian_2011',
    quote: 'Pedimos unos cupcakes sin gluten ni lactosa con diseños personalizados, y no solo estaban deliciosos, si no que el trato al cliente fue excelente, se preocuparon de dejarlo todo claro y fueron muy amables. Muy recomendado',
    avatarSrc: getAvatar('avatar11').src,
    avatarHint: getAvatar('avatar11').hint,
    rating: 5,
  },
  {
    name: 'Sonia Campelo Gómez',
    quote: 'El trato con Emilia fué fantástico, ella se adapta a tus necesidades, Encargué magdalenas que estaban espectaculares, no había comido nada igual.',
    avatarSrc: getAvatar('avatar12').src,
    avatarHint: getAvatar('avatar12').hint,
    rating: 5,
  },
  {
    name: 'Milagros Fernandez',
    quote: 'Una persona increíble, un servicio excelente. Buenas ideas y recomendaciones; un trabajo impecable y ya ni que decir de las delicias de sus postres. INSUPERABLES.',
    avatarSrc: getAvatar('avatar13').src,
    avatarHint: getAvatar('avatar13').hint,
    rating: 5,
  },
  {
    name: 'Tiina Moure',
    quote: '20/10 le mandé a hacer una bola de chocolate relleno de suspiros (rosados o azules) para una revelación de género y fue más de lo esperado. Todo cuidadosamente bien hecho. Recomiendo al 100%',
    avatarSrc: getAvatar('avatar14').src,
    avatarHint: getAvatar('avatar14').hint,
    rating: 5,
  },
  {
    name: 'Jesica',
    quote: 'Nueva pastelería en Ourense que sin duda se convertirá en uno de los sitios de referencia para los amantes del dulce. Donuts, cookies, tartas y semifríos super originales, sabores deliciosos (Lotus, pistacho, etc.) y un local con una decoración preciosa.',
    avatarSrc: getAvatar('avatar15').src,
    avatarHint: getAvatar('avatar15').hint,
    rating: 5,
  },
  {
    name: 'Pedro',
    quote: 'Una muy buena atención, muy agradable y atenta. Muy contento con mi pedido que en este caso fue un tarta de cumpleaños que nos ha encantado tanto el diseño como el sabor. Y tuve la suerte de degustar unas galletas y estaban esquisitas, algo espectacular.',
    avatarSrc: getAvatar('avatar16').src,
    avatarHint: getAvatar('avatar16').hint,
    rating: 5,
  },
  {
    name: 'Maria Jose Jorge Canal',
    quote: 'Las tartas que nos hizo fueron un acierto. Cuidando cada detalle y con un sabor riquísimo. Muchas gracias Emilia.',
    avatarSrc: getAvatar('avatar17').src,
    avatarHint: getAvatar('avatar17').hint,
    rating: 5,
  },
  {
    name: 'Daria Petronela',
    quote: 'Muy contentos con nuestra compra quedamos contentos y todo fue bonito gracias por todo 🫶🏻',
    avatarSrc: getAvatar('avatar18').src,
    avatarHint: getAvatar('avatar18').hint,
    rating: 5,
  },
  {
    name: 'vanesika mallo',
    quote: 'Muy buena pastelería me hizo un pastel personalizado muy bonito sin duda alguna repetiré, lo recomiendo 100%100',
    avatarSrc: getAvatar('avatar19').src,
    avatarHint: getAvatar('avatar19').hint,
    rating: 5,
  },
  {
    name: 'manuel pumar',
    quote: 'La atención, la amabilidad y el asesoramiento por parte de Emilia fue genial, encargue unas galletas personalizadas para las chicas/os de planta del hospital Cosaga por la atención recibida.',
    avatarSrc: getAvatar('avatar20').src,
    avatarHint: getAvatar('avatar20').hint,
    rating: 5,
  },
  {
    name: 'Roberto Santamaría',
    quote: 'Lo conocimos gracias a las reseñas de Google. Tartas y dulces con un toque diferente, y delicioso. Celebramos el cumpleaños de nuestra hija, con un taller de repostería. El trato y la atención fueron inmejorables.',
    avatarSrc: getAvatar('avatar21').src,
    avatarHint: getAvatar('avatar21').hint,
    rating: 5,
  },
  {
    name: 'Susan peña',
    quote: 'La tarta estuvo muy rica y fue una pieza central en la decoración excelente.',
    avatarSrc: getAvatar('avatar22').src,
    avatarHint: getAvatar('avatar22').hint,
    rating: 5,
  },
  {
    name: 'María Belen García Rebollo',
    quote: 'Atención estupenda, presentación espectacular, sabores exquisitos e innovadores, la número uno de la ciudad, una de las mejores pastelera de Ourense .muy creativa',
    avatarSrc: getAvatar('avatar23').src,
    avatarHint: getAvatar('avatar23').hint,
    rating: 5,
  },
  {
    name: 'Rocio Gonzalez Mediavilla',
    quote: 'Esta mañana mi hija recogió una caja de macaron,y espectacular. Nada que ver con lo que vende a otras tiendas y súper. Están muy bonitos y esta claro que repetiremos.',
    avatarSrc: getAvatar('avatar24').src,
    avatarHint: getAvatar('avatar24').hint,
    rating: 5,
  },
  {
    name: 'Flor Medina Chuero',
    quote: 'Muy buen trato del personal, tuve la oportunidad de ganar un concurso en redes, las galletas estaban deliciosas, cada detalle muy bien cuidado, y a mi hija le ha encantado.',
    avatarSrc: getAvatar('avatar25').src,
    avatarHint: getAvatar('avatar25').hint,
    rating: 5,
  },
  {
    name: 'Angie Rubio',
    quote: 'Hemos pedido una tarta a última hora para un cumpleaños y la experiencia no pude ser mejor. La tarta hermosa y el sabor inmejorable, sin duda repetiremos.',
    avatarSrc: getAvatar('avatar26').src,
    avatarHint: getAvatar('avatar26').hint,
    rating: 5,
  },
  {
    name: 'MARÍA LOZANO GONZÁLEZ',
    quote: 'La tarta de queso espectacular. No había probado algo igual. Merece la pena comprar dulces ahí. Un 10 y repetiré',
    avatarSrc: getAvatar('avatar27').src,
    avatarHint: getAvatar('avatar27').hint,
    rating: 5,
  },
  {
    name: 'Irene Meléndez Prada',
    quote: 'Tenía poco tiempo para realizar el encargo y la repostera me atendió súper amable y me enseñó los trabajos que ella realiza y tuvo mucha paciencia para explicarme y que quedara todo perfecto como yo quería! Desde luego es un sitio al que volvería y lo recomiendo al 1000%. Y las galletas personalizadas que encargué súper súper buenas',
    avatarSrc: getAvatar('avatar28').src,
    avatarHint: getAvatar('avatar28').hint,
    rating: 5,
  },
  {
    name: 'Itxaso Etxebarri Barreiro',
    quote: 'Una atención increíble!! Unas galletas deliciosas y la tarta una delicia!! Nos encantó!!! La recomiendo para cualquier evento, quedamos encantadísimos! Gracias por el gran trabajo que has hecho!',
    avatarSrc: getAvatar('avatar29').src,
    avatarHint: getAvatar('avatar29').hint,
    rating: 5,
  },
  {
    name: 'Tabitha Waldron',
    quote: 'Todo muy bonito y super rico!!',
    avatarSrc: getAvatar('avatar30').src,
    avatarHint: getAvatar('avatar30').hint,
    rating: 5,
  },
  {
    name: 'GIANCARLO PAGANO',
    quote: 'excelente torta , tarta para el bautizo de mi hija , es un fenomeno',
    avatarSrc: getAvatar('avatar31').src,
    avatarHint: getAvatar('avatar31').hint,
    rating: 5,
  },
  {
    name: 'Giancarlo Pagano',
    quote: 'Lo maximo lo mejor 6 estrellas',
    avatarSrc: getAvatar('avatar32').src,
    avatarHint: getAvatar('avatar32').hint,
    rating: 5,
  },
  {
    name: 'Najjar',
    quote: 'Estaba súper delicioso y tan bien hecho que ni siquiera pensarías que es real, realmente perfecto y con un sabor excelente.',
    avatarSrc: getAvatar('avatar33').src,
    avatarHint: getAvatar('avatar33').hint,
    rating: 5,
  },
  {
    name: 'Raquel Alvarellos',
    quote: 'Profesionalidad desde el minuto uno. Hace realidad lo que le pides en una tarta, además el sabor que me recordó ha gustado a toda la familia.',
    avatarSrc: getAvatar('avatar34').src,
    avatarHint: getAvatar('avatar34').hint,
    rating: 5,
  },
  {
    name: 'Krisvany Linarez',
    quote: '20/10 quedo muy linda y el sabor increible, la súper recomiendo',
    avatarSrc: getAvatar('avatar35').src,
    avatarHint: getAvatar('avatar35').hint,
    rating: 5,
  },
  {
    name: 'Bacardimen Rodriguez Perez',
    quote: 'Expectacular trabajo por parte de sus profesionales, muy atentos en todo detalle...',
    avatarSrc: getAvatar('avatar36').src,
    avatarHint: getAvatar('avatar36').hint,
    rating: 5,
  },
  {
    name: 'Milainys Torres',
    quote: 'Sabores exquisitos, presentación espectacular 10 de 10',
    avatarSrc: getAvatar('avatar37').src,
    avatarHint: getAvatar('avatar37').hint,
    rating: 5,
  },
  {
    name: 'Gianni M',
    quote: 'Muy ricos los mousse de mango!',
    avatarSrc: getAvatar('avatar38').src,
    avatarHint: getAvatar('avatar38').hint,
    rating: 5,
  },
  {
    name: 'Veronica Afonso Rodríguez',
    quote: 'Quería felicitar mortyscake por tan maravilloso taller infantil de repostería. Cada detalle, Pulcritud e imaginación al máximo. Los niños se la pasaron genial y el resultado, unas galletas riquísimas... Mereció la pena y volveremos al próximo. Felicidades y que sigan los éxitos.',
    avatarSrc: getAvatar('avatar39').src,
    avatarHint: getAvatar('avatar39').hint,
    rating: 5,
  },
  {
    name: 'Emilia Costela',
    quote: 'Me ha encantado el local, los postres impresionantes, es más degusté una maravilloso tarta de Nutella y allí aparte del cupcake de maracuyá, el café muy muy bueno. La atención de Emilia de 10 y sin lugar a dudas volveré y lo recomiendo al 100 por cien.',
    avatarSrc: getAvatar('avatar40').src,
    avatarHint: getAvatar('avatar40').hint,
    rating: 5,
  },
  {
    name: 'Luu Ds',
    quote: 'muy amable, muy atenta y muy rico y bonito todo.',
    avatarSrc: getAvatar('avatar41').src,
    avatarHint: getAvatar('avatar41').hint,
    rating: 5,
  },
  {
    name: 'Alicia Rodríguez',
    quote: 'De las mejores pastelerías de Ourense, dueña amable y con muy buena mano para las tartas. 100% recomendable.',
    avatarSrc: getAvatar('avatar42').src,
    avatarHint: getAvatar('avatar42').hint,
    rating: 5,
  },
  {
    name: 'lidia gomez carballo',
    quote: 'Un trato, ambiente, servicio y un producto increíble calidad precio. Todo un gusto de decoración y trabajo . Ánimo a todo el mundo a venir a probarlo.',
    avatarSrc: getAvatar('avatar43').src,
    avatarHint: getAvatar('avatar43').hint,
    rating: 5,
  },
  {
    name: 'Impresion Grafica',
    quote: 'Sus cookies y sus mousse son excelentes con esos sabores tropicales es una explosión de sabores diferentes en tu paladar es una experiencia única en sus postres, y así como son sus postres es Emilia la repostera protagonista de su local.',
    avatarSrc: getAvatar('avatar44').src,
    avatarHint: getAvatar('avatar44').hint,
    rating: 5,
  },
  {
    name: 'Verónica Iglesias',
    quote: 'Quedé encantada con el trabajo que realizó, muy rica y bonita la tarta',
    avatarSrc: getAvatar('avatar45').src,
    avatarHint: getAvatar('avatar45').hint,
    rating: 5,
  },
  {
    name: 'MATIAS GARCIA FANTINI',
    quote: 'Una excelente atención con un excelente producto. Un 10 de 10.',
    avatarSrc: getAvatar('avatar46').src,
    avatarHint: getAvatar('avatar46').hint,
    rating: 5,
  },
  {
    name: 'Andrea Estévez',
    quote: 'Sitio muy agradable y con dulces deliciosos. Si pides café puedes hacerte un selfie e "imprimirla" en él, muy original. Repetiremos.',
    avatarSrc: getAvatar('avatar47').src,
    avatarHint: getAvatar('avatar47').hint,
    rating: 5,
  },
  {
    name: 'Elio Villalobos Manzo',
    quote: 'La mejor pastelería gourmet de Ourense. Me tomé una foto y la imprimieron en mi taza de café, súper originales y está muy guay.',
    avatarSrc: getAvatar('avatar48').src,
    avatarHint: getAvatar('avatar48').hint,
    rating: 5,
  },
  {
    name: 'Lucia Medin',
    quote: 'Un servicio al cliente excepcional, postres deliciosos y un maravillosos café personalizado. Altamente recomendado.',
    avatarSrc: getAvatar('avatar49').src,
    avatarHint: getAvatar('avatar49').hint,
    rating: 5,
  },
  {
    name: 'Miriam Carballo Novoa',
    quote: 'el ambiente, comida y servicio son 10/10 es un sitio súper cálido y una comida sana y saludable ideal para pasar un buen rato',
    avatarSrc: getAvatar('avatar50').src,
    avatarHint: getAvatar('avatar50').hint,
    rating: 5,
  },
  {
    name: 'SAUL RODRIGUEZ',
    quote: 'Un sitio maravilloso para pasar la tarde,tomandose un buen cafe y comiendo unos deliciosos postres, lo recomiendo enormemente!',
    avatarSrc: getAvatar('avatar51').src,
    avatarHint: getAvatar('avatar51').hint,
    rating: 5,
  },
  {
    name: 'Rafael Jose Pineda Medina',
    quote: 'Me encanta el sitio, desde ya puedo decir que se ha convertido en uno de mis sitios favoritos, 100% recomendable',
    avatarSrc: getAvatar('avatar52').src,
    avatarHint: getAvatar('avatar52').hint,
    rating: 5,
  },
  {
    name: 'Fabiola Palacio',
    quote: 'Café delicioso que te hace sentir como en casa 💖💖💖',
    avatarSrc: getAvatar('avatar53').src,
    avatarHint: getAvatar('avatar53').hint,
    rating: 5,
  },
  {
    name: 'Maria de los Los Ángeles Cordero López',
    quote: 'Todo del más allá😍🥰!! Todo espectacular, los mejores postres de Ourense🫶🏻😍😍😍',
    avatarSrc: getAvatar('avatar54').src,
    avatarHint: getAvatar('avatar54').hint,
    rating: 5,
  },
  {
    name: 'La negra',
    quote: 'Excelente lo mejor',
    avatarSrc: getAvatar('avatar55').src,
    avatarHint: getAvatar('avatar55').hint,
    rating: 5,
  },
  {
    name: 'Yasmeiri Mariñez Garcia',
    quote: 'Me encantó, el sitio super bonito y con todo riquísimo',
    avatarSrc: getAvatar('avatar56').src,
    avatarHint: getAvatar('avatar56').hint,
    rating: 5,
  },
  {
    name: 'draco men',
    quote: 'Me gustó mucho la tarta de lavanda, sería marivolloso que lo probaira',
    avatarSrc: getAvatar('avatar57').src,
    avatarHint: getAvatar('avatar57').hint,
    rating: 5,
  },
  {
    name: 'Yaser PM',
    quote: 'Me flipó el sitio, que te puedan hacer diseños en el café es increíble 😁',
    avatarSrc: getAvatar('avatar58').src,
    avatarHint: getAvatar('avatar58').hint,
    rating: 5,
  },
  {
    name: 'Darmian 61',
    quote: 'El mejor!!!!',
    avatarSrc: getAvatar('avatar59').src,
    avatarHint: getAvatar('avatar59').hint,
    rating: 5,
  },
  {
    name: 'Marvin Rivero',
    quote: 'Excelente todo, la recomiendo totalmente, elaboro nuestra tarta de matrimonio y tanto yo, como mi novio quedamos encantados y satisfechos.',
    avatarSrc: getAvatar('avatar60').src,
    avatarHint: getAvatar('avatar60').hint,
    rating: 5,
  },
  {
    name: 'elhyli alexandra hernandez sepulveda',
    quote: '',
    avatarSrc: getAvatar('avatar61').src,
    avatarHint: getAvatar('avatar61').hint,
    rating: 5,
  },
  {
    name: 'Diego Caride',
    quote: '',
    avatarSrc: getAvatar('avatar62').src,
    avatarHint: getAvatar('avatar62').hint,
    rating: 5,
  },
  {
    name: 'Dirección SBM',
    quote: '',
    avatarSrc: getAvatar('avatar63').src,
    avatarHint: getAvatar('avatar63').hint,
    rating: 5,
  },
  {
    name: 'María González Conde',
    quote: '',
    avatarSrc: getAvatar('avatar64').src,
    avatarHint: getAvatar('avatar64').hint,
    rating: 5,
  },
  {
    name: 'Adriana C',
    quote: '',
    avatarSrc: getAvatar('avatar65').src,
    avatarHint: getAvatar('avatar65').hint,
    rating: 5,
  }
];

    